### ISSUE TITLE
Improve the check configuration format

### ISSUE THREAD

**Issue by DarkAtra** [DarkAtra/project-overview-hackday#2]
As of right now we are using the `application.yml` to store the configuration for checks like this:

```
repository:
    project: foo
    checks:
      - type: parent
        id: 1
        name: Spring Boot Parent
        required: true
        artifact:
          group-id: org.springframework.boot
          artifact-id: spring-boot-starter-parent
          version-resolver:
            type: url
            url: https://repo1.maven.org/maven2
    check-overrides:
      - repository: bar
        excluded-checks: [1]
```

This currently limits us in the ability to add/edit/delete checks or enable/disable them for some repositories on the fly.
